name: Meu primeiro workflow

on: push

jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Este job foi criado por causa do ${{ github.event_name }}."
      - run: echo "🐧 Este job está rodando no servidor ${{ runner.os }} diretamente no Github!"
      - run: echo "🔎 O nome da sua branch é ${{ github.ref }} e sua repo é ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 A repo ${{ github.repository }} foi clonada para a esteira."
      - run: echo "🖥️ O workflow está pronto para rodar o código."
      - name: Lista de arquivos no repositório
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 O status deste job é ${{ job.status }}."

  job-de-teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - run: echo "🎉 Este job foi criado por causa do ${{ github.event_name }}."
      - run: echo "🐧 Este job está rodando no servidor ${{ runner.os }} diretamente no Github!"
      - run: echo "🔎 O nome da sua branch é ${{ github.ref }} e sua repo é ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Mostrando a versão do Python
        run: python -c "import sys; print(sys.version)"
      - name: Teste com Pytest
        run: |
          pip install pytest pytest-cov
          pytest tests/test_geometria.py
      - run: echo "🍏 O status deste job é ${{ job.status }}."