name: 2 - Workflow para Homologação  # Nome do workflow para homologação

on:
  push:  # Aciona o workflow em caso de push
    branches:
      - develop  # O workflow é executado apenas na branch develop

jobs:
  release:  # Definição do job para criar uma nova release
    runs-on: ubuntu-latest  # Define o ambiente para execução (Ubuntu)

    steps:
      - name: Checkout do repositório  # Passo para fazer checkout do repositório
        uses: actions/checkout@v3  # Usa a ação padrão para fazer checkout do código

      - name: Configurar Identidade do Git  # Configura a identidade do Git
        run: |  # Executa os comandos abaixo em um shell
          git config --global user.email "seu-email@example.com"  # Configure seu e-mail aqui
          git config --global user.name "Seu Nome"  # Configure seu nome aqui

      - name: Obter a última release  # Obtém a última tag de release
        run: |  # Executa os comandos abaixo em um shell
          last_release=$(git tag | sort -V | tail -n 1)  # Obtém a última tag de release
          echo "Última release: $last_release"  # Mostra a última release nos logs

      - name: Criar nova branch de release  # Cria uma nova branch de release
        run: |  # Executa os comandos abaixo em um shell
          new_release=$(echo "$last_release" | awk -F. -v OFS=. '{$NF++; print}')  # Incrementa a última tag
          git checkout -b "release-$new_release"  # Cria a nova branch de release

      - name: Puxar atualizações remotas  # Puxa atualizações da branch remota
        run: |  # Executa os comandos abaixo em um shell
          git pull origin "release-$new_release" || echo "Não há novas alterações para puxar."  # Puxa as alterações da branch de release

      - name: Fazer push da nova branch  # Faz push da nova branch de release
        run: |  # Executa os comandos abaixo em um shell
          git push origin "release-$new_release"  # Faz push da nova branch de release
