name: Test and Create PR for Homologation  # Nome do workflow para testes e criação de Pull Request para homologação

on:
  push:  # Aciona o workflow em caso de push
    branches:
      - develop  # O workflow é executado apenas na branch 'develop'

jobs:
  run-tests:  # Job para executar os testes
    runs-on: ubuntu-latest  # Define o ambiente para execução (Ubuntu)

    steps:
      - name: Checkout do repositório  # Passo para fazer checkout do repositório
        uses: actions/checkout@v3  # Usa a ação padrão para fazer checkout do código

      - name: Configurar o Python  # Passo para configurar a versão do Python
        uses: actions/setup-python@v4  # Usa a ação para configurar o ambiente Python
        with:
          python-version: '3.9'  # Define a versão do Python a ser usada

      - name: Instalar dependências  # Passo para instalar as dependências do projeto
        run: |  # Executa os comandos abaixo em um shell
          python -m pip install --upgrade pip  # Atualiza o pip para a versão mais recente
          pip install -r requirements.txt  # Instala as dependências listadas no arquivo requirements.txt

      - name: Rodar testes unitários  # Passo para rodar os testes unitários
        run: |  # Executa os comandos abaixo em um shell
          pytest tests/test_geometria.py  # Executa os testes unitários localizados no diretório tests

  create-release-branch:  # Job para criar uma nova branch de release
    runs-on: ubuntu-latest  # Define o ambiente para execução (Ubuntu)
    needs: run-tests  # Este job depende que o job 'run-tests' tenha sido concluído com sucesso
    if: success()  # Somente cria a branch de release se os testes passarem

    steps:
      - name: Checkout do repositório  # Passo para fazer checkout do repositório novamente
        uses: actions/checkout@v3  # Necessário para garantir que o repositório esteja disponível para a criação da nova branch

      - name: Obter número da versão atual  # Passo para obter a versão atual da release
        id: get-version  # Atribui um ID a este passo para referenciá-lo posteriormente
        run: |  # Executa os comandos abaixo em um shell
          # Obtém a última tag de release, remove o prefixo 'release-' e a converte em um número
          version=$(git tag --list 'release-*' | sort -V | tail -n 1 | sed 's/release-//')
          # Se não houver versão, inicia a contagem a partir de 0
          if [ -z "$version" ]; then
            version=0
          fi
          # Incrementa o número da versão
          new_version=$((version + 1))
          # Define a nova versão como uma saída para uso posterior
          echo "::set-output name=new_version::release-${new_version}"

      - name: Criar nova branch de release  # Passo para criar uma nova branch de release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa o token de autenticação do GitHub para push
        run: |  # Executa os comandos abaixo em um shell
          # Cria uma nova branch com base na nova versão obtida
          git checkout -b ${{ steps.get-version.outputs.new_version }}  # Cria uma nova branch com o nome da nova versão
          # Faz push da nova branch para o repositório remoto
          git push origin ${{ steps.get-version.outputs.new_version }}  # Faz push da nova branch de releas
