name: Test and Create PR for Homologation

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes unitários
        run: |
          pytest tests/test_geometria.py

  create-release-branch:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()  

    steps:
      - name: Obter número da versão atual
        id: get-version
        run: |
          # Extrair o número da versão mais recente do histórico de releases
          version=$(git tag --list 'release-*' | sort -V | tail -n 1 | sed 's/release-//')
          if [ -z "$version" ]; then
            version=0
          fi
          new_version=$((version + 1))
          echo "::set-output name=new_version::release-${new_version}"

      - name: Criar nova branch de release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b ${{ steps.get-version.outputs.new_version }}
          git push origin ${{ steps.get-version.outputs.new_version }}