name: Test and Create PR for Production

on:
  push:
    branches:
      - hom

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes unitários
        run: |
          pytest tests/test_geometria.py

  create-prod-pr:
    runs-on: ubuntu-latest
    needs: run-tests

    if: success()  # Executa somente se os testes passarem

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar PR automática para Produção
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base prod --head hom --title "Merge to Production: Homologation Branch" --body "$(cat .github/pull_request_template.md)"