name: Create PR for Homologation

on:
  push:
    branches:
      - dev

jobs:
  create-hom-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar PR automática para Homologação
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base hom --head dev --title "Merge to Homologation: Dev Branch" --body "$(cat .github/pull_request_template.md)"