name: 2 - Workflow para Hom  # Nome do workflow para homologação

on:
  push:
    branches:
      - develop  # O workflow é acionado apenas na branch 'develop'

jobs:
  run-tests:  # Job para executar os testes
    runs-on: ubuntu-latest  # Define o ambiente para execução

    steps:
      - name: Checkout do repositório  # Clona o repositório
        uses: actions/checkout@v3

      - name: Configurar o Python  # Configura a versão do Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Define a versão do Python

      - name: Instalar dependências  # Instala as dependências do projeto
        run: |
          python -m pip install --upgrade pip  # Atualiza o pip
          pip install -r requirements.txt  # Instala as dependências

      - name: Rodar testes unitários  # Executa os testes
        run: |
          pytest tests/

  create-release-pr:
    runs-on: ubuntu-latest
    needs: run-tests  # Aguarda a conclusão do job de testes
    if: success()  # Só cria a PR se os testes passarem

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3  # Clona o repositório novamente para garantir o estado atualizado

      - name: Criar Pull Request para a branch release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release  # Cria a branch release
          git push origin release  # Faz push da branch release
          gh pr create --base main --head release --title "Release" --body "Pull Request para a branch de release"  # Cria a PR
