name: Create PR for Homologation

on:
  push:
    branches:
      - develop

jobs:
  create-hom-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes unitários
        run: |
          pytest tests/test_geometria.py

      - name: Criar PR automática para Homologação
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base hom --head develop --title "Merge to Homologation: Dev Branch" --body "$(cat .github/pull_request_template.md)"